apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
        - name: web
          image: swennie/simple-site:4d9c63d815c7938571a74f00c83487a9f814c3f2
          ports:
            - containerPort: 80
