apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
        - name: web
          image: swennie/simple-site:b7a89c6e802dd472efa9f6f758eb4d3fe1fdbecd
          ports:
            - containerPort: 80
