# Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
      version: blue
  template:
    metadata:
      labels:
        app: simple-website
        version: blue
    spec:
      containers:
        - name: web
          image: swennie/simple-site:4c1a40a4ccd955be0fdbc9eab33c033460043c7e
          ports:
            - containerPort: 80

---

# Green Deployment (update image when deploying new version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
      version: green
  template:
    metadata:
      labels:
        app: simple-website
        version: green
    spec:
      containers:
        - name: web
          image: swennie/simple-site:4c1a40a4ccd955be0fdbc9eab33c033460043c7e
          ports:
            - containerPort: 80
