# Service to route traffic
apiVersion: v1
kind: Service
metadata:
  name: simple-website-service
spec:
  selector:
    app: simple-website
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
