name: Build and Deploy to Kubernetes (ArgoCD GitOps)

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "k8s/**"

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-site:${{ steps.vars.outputs.TAG }} ./app

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-site:${{ steps.vars.outputs.TAG }}

      - name: Update Kubernetes deployment image tag
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/simple-site:${{ steps.vars.outputs.TAG }}|g" k8s/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config user.name "${{ secrets.GIT_NAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.TAG }}"
          git push
